# k8s/discord-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
type: Opaque
data:
  # ATENÇÃO: COPIE A STRING BASE64 ABAIXO COMO UMA LINHA ÚNICA
  webhook-url: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQ1MDIwNTAyMTI1MjYxNjM0MC9uZjZmMUNxdXd1Qi03SkNuV3planpHQWZKWk8tTktJY0xnNTJUQTIzTG1Pdy1pQ0V5N25BWGpQLW1lR1F5bHF5MHVQNg==